test:
  user: 'fedoraAdmin'
  password: 'fedoraAdmin'
  host: 'localhost'
  port: 8983
  context: 'fedora'

development:
  user: 'fedoraAdmin'
  password: 'fedoraAdmin'
  host: 'localhost'
  port: 8983
  context: 'fedora'

production:
  user: 'fedoraAdmin'
  password: 'fedoraAdmin'
  host: 'localhost'
  port: 8983
  context: 'fedora'
